name: Update AUR Package
description: Create a AUR release on version bump
author: varabyte
branding:
  color: blue
  icon: navigation-2
inputs:
  dry_run:
    description: Whether to actually upload the AUR release or just log.
    required: false
    default: "false"
  version:
    description: The version to use for this release, without any prefixes (e.g. `1.2.3`).
    required: true
  package_name:
    description: The name of the AUR package to update.
    required: true
  commit_username:
    description: The username to use when creating the new commit.
    required: true
  commit_email:
    description: The email to use when creating the new commit.
    required: true
  ssh_private_key:
    description: The SSH private key with access to the specified AUR package.
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.tag_dry_run }} ${{ inputs.tag_version_prefix }} ${{ inputs.package_name }} ${{ inputs.commit_username }} ${{ inputs.commit_email }} ${{ inputs.ssh_private_key }}
